<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-G2TLUC4" ignored="0" name="Default test" tests="1" failures="1" timestamp="09 六月 2017 08:25:36 GMT" time="0.581" errors="0">
  <testcase name="test_method" time="0.565" classname="com.zzy.Interface.Test_Interface">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: test_method([])
Arguments: [(java.lang.String)Enable,(java.lang.String)NO,(java.lang.String)Name,(java.lang.String)Http,(java.lang.String)Path,(java.lang.String)Tpye,(java.lang.String)Input,(java.lang.String)Expect Output,(java.lang.String)Autal Output,(java.lang.String)error_code,(java.lang.String)error_message,(java.lang.String)Result]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: test_method([])
Arguments: [(java.lang.String)Enable,(java.lang.String)NO,(java.lang.String)Name,(java.lang.String)Http,(java.lang.String)Path,(java.lang.String)Tpye,(java.lang.String)Input,(java.lang.String)Expect Output,(java.lang.String)Autal Output,(java.lang.String)error_code,(java.lang.String)error_message,(java.lang.String)Result]
	at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:49)
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1293)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1187)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- test_method -->
</testsuite> <!-- Default test -->
